# NOTE: This files shows a possible production setup.
#       If you are not familiar with handling containers in production, please 
#       consider a different approach of hosting. This setup can lead to 
#       errors and loss of production data if handled incorrectly. Currently 

# WARNING: Currently, container based setups are not officially supported by Humhub GmbH.
#          Use at your own risk!
version: '3.1'
services:
  nginx:
    image: docker.io/mriedmann/humhub:stable-nginx
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - "uploads:/var/www/localhost/htdocs/uploads"
      - "assets:/var/www/localhost/htdocs/assets"
      - "modules:/var/www/localhost/htdocs/protected/modules"
      - "themes:/var/www/localhost/htdocs/themes"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  humhub:
    image: docker.io/lukaskel/postavljen-docker:latest
    expose:
      - '9000'
    environment:
      HUMHUB_DB_HOST: 'db'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 0
      # HUMHUB_DEBUG: 1 # you can currently not use debug in prod 
      HUMHUB_PROTO: 'https'
      HUMHUB_HOST: 'localhost'
      # Mailer install setup
      HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS: 'festival@kuzek.si'
      HUMHUB_MAILER_SYSTEM_EMAIL_NAME: 'Kuzkov Festival'
      HUMHUB_MAILER_TRANSPORT_TYPE: 'smtp'
      #HUMHUB_MAILER_HOSTNAME: 'mailer'
      #HUMHUB_MAILER_PORT: 587
      #HUMHUB_MAILER_USERNAME: 'festival@kuzek.si'
      #HUMHUB_MAILER_PASSWORD: ''
      HUMHUB_MAILER_ALLOW_SELF_SIGNED_CERTS: 0
      # Cache Config
      HUMHUB_CACHE_EXPIRE_TIME: 3600
      HUMHUB_CACHE_CLASS: yii\redis\Cache
      HUMHUB_QUEUE_CLASS: humhub\modules\queue\driver\Redis
      HUMHUB_REDIS_HOSTNAME: redis
      HUMHUB_REDIS_PORT: 6379
      HUMHUB_REDIS_PASSWORD: redis_password
      PHP_POST_MAX_SIZE: '16M'
      PHP_UPLOAD_MAX_FILESIZE: '16M'
      PHP_MEMORY_LIMIT: '256M'

    volumes:
      - "uploads:/var/www/localhost/htdocs/uploads"
      - "assets:/var/www/localhost/htdocs/assets"
      - "modules:/var/www/localhost/htdocs/protected/modules"
      - "themes:/var/www/localhost/htdocs/themes"
#     - "${HUMHUB_VOLUME_CONFIG}:/var/www/localhost/htdocs/protected/config"
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ../sqldata:/var/lib/mysql
  mailer:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - 1025
    ports:
      - "1080:1080"
  redis:
    image: redis:5.0-alpine
    expose:
      - '6379'
#    volumes:
#      - /srv/humhub/redis:/data
    environment:
      - REDIS_PASSWORD=redis_password
      #- ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
volumes:
  uploads: {}
  assets: {}
  modules: {}
  themes: {}
